# yaml-language-server: $schema=https://www.***REMOVED***.sh/schema/manifest.json
---
model:
  version: 3

types:
  user:
    relations:
      delegate: agent

  agent: {}

  workflow:
    relations:
      owner: user
    permissions:
      # Direct ownership check - used for anti-spoofing
      # A user is_owner if they have the owner relation to the workflow
      is_owner: owner
      
      # Agent can execute if the workflow owner has delegated to that agent.
      can_execute: owner->delegate

  workflow_item:
    relations:
      workflow: workflow
    permissions:
      # Delegate execution permission to the workflow’s can_execute permission.
      can_execute: workflow->can_execute